(+ (+ (+ (+ (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))
            (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))))
         (+ (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))
            (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))))
      (+ (+ (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))
            (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))))
         (+ (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))
            (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))))))
   (+ (+ (+ (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))
            (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))))
         (+ (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))
            (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))))
      (+ (+ (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))
            (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))))
         (+ (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))
            (+ (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))))
               (+ (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))
                  (+ (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read))))
                     (+ (+ (+ (read) (read))
                           (+ (read) (read)))
                        (+ (+ (read) (read))
                           (+ (read) (read)))))))))))
